INSERT IGNORE INTO record_field_defs(record_type, field_key, sort_order)
VALUES
  ('purchase', '下单日期', 1),
  ('purchase', '产品图片', 2),
  ('purchase', '公司物料代码', 3),
  ('purchase', '出货标签条码', 4),
  ('purchase', '账号', 5),
  ('purchase', 'SKU货号', 6),
  ('purchase', '规格/颜色/配置', 7),
  ('purchase', '产品包装规格', 8),
  ('purchase', '采购价格（元）', 9),
  ('purchase', '下单数', 10),
  ('purchase', '发货安排套/箱', 11),
  ('purchase', '产品信息-备注', 12),
  ('purchase', '交期明细-交货日期', 13),
  ('purchase', '交货数量', 14),
  ('purchase', '出货箱数', 15),
  ('purchase', '剩余未交数量', 16),
  ('purchase', '订单金额/付款方式', 17),
  ('purchase', '付款明细-订单总金额', 18),
  ('purchase', '预付', 19),
  ('purchase', '尾款', 20),
  ('purchase', '运费', 21),
  ('purchase', '阿里订单号', 22),
  ('purchase', '采购', 23),
  ('purchase', '供应商/链接', 24),
  ('purchase', '其他备注', 25);
