INSERT IGNORE INTO record_field_defs(record_type, field_key, sort_order)
VALUES
  ('sales_ops', '运营人员', 1),
  ('sales_ops', '店铺名称', 2),
  ('sales_ops', '产品名称', 3),
  ('sales_ops', 'SKC', 4),
  ('sales_ops', 'SKU', 5),
  ('sales_ops', '产品规格', 6),
  ('sales_ops', '链接标签', 7),
  ('sales_ops', '浏览量', 8),
  ('sales_ops', '点击量', 9),
  ('sales_ops', '点击率', 10),
  ('sales_ops', '成交量', 11),
  ('sales_ops', '成交率', 12),
  ('sales_ops', '是否被限流', 13),
  ('sales_ops', '限流原因', 14),
  ('sales_ops', '解限流方案', 15),
  ('sales_ops', 'SKU成本价', 16),
  ('sales_ops', '备注说明', 17),
  ('sales_ops', '标签状态分析码', 18),
  ('sales_ops', '限流状态分析码', 19),
  ('sales_ops', '创建时间', 20),
  ('sales_ops', '父记录', 21),
  ('sales_ops', '父记录 2', 22);
