export type WorkspaceSchema = {
  key: string;
  title: string;
  fields: string[];
};

export const PURCHASE_FIELDS: string[] = [
  "名称",
  "产品图片",
  "参考链接",
  "平台在售价格（Min）",
  "平台在售价格（Max）",
  "所属类目",
  "产品规格",
  "产品链接×",
  "预计周平均日销量",
  "资质要求",
  "是否有专利风险",
  "选品逻辑",
  "选品人",
  "询价分配人｜选品",
  "询价人",
  "产品尺寸-长（厘米）",
  "产品尺寸-宽（厘米）",
  "产品尺寸-高（厘米）",
  "包装尺寸-长（英寸）",
  "包装尺寸-宽（英寸）",
  "包装尺寸-高（英寸）",
  "产品体积",
  "产品重量",
  "产品实物图",
  "包裹尺寸-长（厘米）",
  "包裹尺寸-宽（厘米）",
  "包裹尺寸-高（厘米）",
  "包裹体积（立方厘米）",
  "体积重系数",
  "体积重",
  "包裹实重（公斤）",
  "包裹计费重",
  "包裹计费重（磅）",
  "包裹尺寸-长（英寸）",
  "包裹尺寸-宽（英寸）",
  "包裹尺寸-高（英寸）",
  "包裹实物包装图",
  "箱规",
  "运输包装尺寸-长（厘米）",
  "运输包装尺寸-宽（厘米）",
  "运输包装尺寸-高（厘米）",
  "运输包装体积",
  "运输包装体积系数",
  "运输包装体积重",
  "运输包装实重",
  "运输包装计费重",
  "产品单价",
  "起订量",
  "优惠政策",
  "交货周期",
  "资质情况",
  "专利情况",
  "工厂所在地",
  "工厂联系人",
  "联系人电话",
  "海外仓（卸货费）",
  "海外仓（操作费）",
  "派送费（需要测试？）",
  "美元汇率",
  "尾程成本（人民币）",
  "头程单价（人民币）？",
  "头程成本",
  "采购成本",
  "负向成本",
  "成本总计",
  "人民币报价",
  "temu核价最低标准（未加2.99）",
  "temu报价",
  "temu售价",
  "卖价",
  "状态",
  "运营人员",
  "创建时间",
  "最后更新时间",
];

export const SELECTION_CANDIDATE_FIELDS: string[] = [
  "名称",
  "产品图片",
  "参考链接",
  "平台在售价格（Min）",
  "平台在售价格（Max）",
  "所属类目",
  "产品规格",
  "产品链接×",
  "预计周平均日销量",
  "资质要求",
  "是否有专利风险",
  "选品逻辑",
  "选品人",
  "状态",
  "创建时间",
  "最后更新时间",
];

export const WORKSPACE_SCHEMAS: WorkspaceSchema[] = [
  { key: "ops.purchase", title: "选品-采购管理表", fields: PURCHASE_FIELDS },
  { key: "ops.selection_candidates", title: "选品备选表", fields: SELECTION_CANDIDATE_FIELDS },
  { key: "ops.inquiry", title: "询价", fields: PURCHASE_FIELDS },
  { key: "ops.pricing", title: "核价", fields: PURCHASE_FIELDS },
];

export function getWorkspaceSchema(key: string) {
  return WORKSPACE_SCHEMAS.find((s) => s.key === key) ?? null;
}
